@php use App\Modules\FixedAssets\Enums\AssetStatus; @endphp
<x-app-layout>
    <x-slot name="header"><div class="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><p class="text-sm font-medium text-indigo-600">Patrimoine</p><h1 class="text-2xl font-semibold text-gray-900">Immobilisations</h1></div><a href="{{ route('fixed-assets.create') }}" class="rounded-lg bg-indigo-600 px-4 py-2.5 text-sm font-semibold text-white">Nouvelle immobilisation</a></div></x-slot>
    <div class="py-10"><div class="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
        <form method="GET" class="mb-6 grid gap-3 rounded-xl bg-white p-4 shadow-sm ring-1 ring-gray-200 sm:grid-cols-[1fr_200px_auto]"><input name="search" value="{{ $search }}" placeholder="Code ou désignation" class="rounded-md border-gray-300"><select name="status" class="rounded-md border-gray-300"><option value="">Tous les statuts</option>@foreach (AssetStatus::cases() as $item)<option value="{{ $item->value }}" @selected($status === $item->value)>{{ $item->label() }}</option>@endforeach</select><x-secondary-button type="submit">Filtrer</x-secondary-button></form>
        <div class="overflow-hidden rounded-xl bg-white shadow-sm ring-1 ring-gray-200"><div class="overflow-x-auto"><table class="min-w-full divide-y divide-gray-200"><thead class="bg-gray-50"><tr class="text-left text-xs font-semibold uppercase tracking-wide text-gray-500"><th class="px-6 py-3">Bien</th><th class="px-6 py-3">Catégorie</th><th class="px-6 py-3">Mise en service</th><th class="px-6 py-3">Durée</th><th class="px-6 py-3 text-right">Coût</th><th class="px-6 py-3">Statut</th></tr></thead><tbody class="divide-y divide-gray-100">
        @forelse($assets as $asset)<tr><td class="px-6 py-4"><a href="{{ route('fixed-assets.show', $asset) }}" class="font-semibold text-indigo-600">{{ $asset->code }}</a><p class="text-sm text-gray-700">{{ $asset->name }}</p></td><td class="px-6 py-4 text-sm">{{ $asset->category->label() }}</td><td class="px-6 py-4 text-sm">{{ $asset->in_service_date->format('d/m/Y') }}</td><td class="px-6 py-4 text-sm">{{ $asset->useful_life_months }} mois</td><td class="px-6 py-4 text-right font-medium">{{ number_format((float)$asset->acquisition_cost,2,',',' ') }} {{ $asset->currency }}</td><td class="px-6 py-4"><span class="rounded-full bg-gray-100 px-2.5 py-1 text-xs font-medium">{{ $asset->status->label() }}</span></td></tr>
        @empty<tr><td colspan="6" class="px-6 py-14 text-center text-gray-500">Aucune immobilisation enregistrée.</td></tr>@endforelse
        </tbody></table></div>@if($assets->hasPages())<div class="border-t px-6 py-4">{{ $assets->links() }}</div>@endif</div>
    </div></div>
</x-app-layout>
