<x-app-layout>
    <x-slot name="header"><div class="flex items-center justify-between"><div><p class="text-sm font-medium text-indigo-600">{{ $asset->code }}</p><h1 class="text-2xl font-semibold text-gray-900">{{ $asset->name }}</h1></div><a href="{{ route('fixed-assets.edit', $asset) }}" class="rounded-lg border border-gray-300 bg-white px-4 py-2.5 text-sm font-semibold text-gray-700">Modifier</a></div></x-slot>
    <div class="py-10"><div class="mx-auto max-w-6xl px-4 sm:px-6 lg:px-8">
        @if(session('success'))<div class="mb-6 rounded-lg bg-emerald-50 px-4 py-3 text-sm text-emerald-800">{{ session('success') }}</div>@endif
        <div class="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">
            <div class="rounded-xl bg-white p-5 ring-1 ring-gray-200"><p class="text-xs uppercase text-gray-500">Coût d’acquisition</p><p class="mt-2 text-xl font-semibold">{{ number_format((float)$asset->acquisition_cost,2,',',' ') }} {{ $asset->currency }}</p></div>
            <div class="rounded-xl bg-white p-5 ring-1 ring-gray-200"><p class="text-xs uppercase text-gray-500">Base amortissable</p><p class="mt-2 text-xl font-semibold">{{ number_format($asset->depreciableAmount(),2,',',' ') }} {{ $asset->currency }}</p></div>
            <div class="rounded-xl bg-white p-5 ring-1 ring-gray-200"><p class="text-xs uppercase text-gray-500">Amortissement théorique</p><p class="mt-2 text-xl font-semibold">{{ number_format($accumulated,2,',',' ') }} {{ $asset->currency }}</p></div>
            <div class="rounded-xl bg-indigo-950 p-5 text-white"><p class="text-xs uppercase text-indigo-300">Valeur nette théorique</p><p class="mt-2 text-xl font-semibold">{{ number_format($netBookValue,2,',',' ') }} {{ $asset->currency }}</p></div>
        </div>
        <div class="mt-6 rounded-xl bg-white p-6 ring-1 ring-gray-200"><dl class="grid gap-5 sm:grid-cols-3"><div><dt class="text-xs uppercase text-gray-500">Catégorie</dt><dd class="mt-1 font-semibold">{{ $asset->category->label() }}</dd></div><div><dt class="text-xs uppercase text-gray-500">Mise en service</dt><dd class="mt-1 font-semibold">{{ $asset->in_service_date->format('d/m/Y') }}</dd></div><div><dt class="text-xs uppercase text-gray-500">Durée</dt><dd class="mt-1 font-semibold">{{ $asset->useful_life_months }} mois</dd></div><div><dt class="text-xs uppercase text-gray-500">Valeur résiduelle</dt><dd class="mt-1 font-semibold">{{ number_format((float)$asset->residual_value,2,',',' ') }} {{ $asset->currency }}</dd></div><div><dt class="text-xs uppercase text-gray-500">Fournisseur</dt><dd class="mt-1 font-semibold">{{ $asset->supplier?->name ?? '—' }}</dd></div><div><dt class="text-xs uppercase text-gray-500">Statut</dt><dd class="mt-1 font-semibold">{{ $asset->status->label() }}</dd></div></dl></div>
        <div class="mt-6 overflow-hidden rounded-xl bg-white ring-1 ring-gray-200"><div class="border-b px-6 py-5"><h2 class="font-semibold text-gray-900">Plan d’amortissement linéaire</h2><p class="mt-1 text-sm text-gray-500">Projection mensuelle théorique, avant comptabilisation.</p></div><div class="max-h-[600px] overflow-auto"><table class="min-w-full divide-y divide-gray-200"><thead class="sticky top-0 bg-gray-50"><tr class="text-left text-xs uppercase text-gray-500"><th class="px-6 py-3">Échéance</th><th class="px-6 py-3 text-right">Dotation</th><th class="px-6 py-3 text-right">Cumul</th><th class="px-6 py-3 text-right">Valeur nette</th></tr></thead><tbody class="divide-y divide-gray-100">@foreach($schedule as $row)<tr class="{{ $row['period']->isPast() ? 'bg-gray-50' : '' }}"><td class="px-6 py-3">{{ $row['period']->format('d/m/Y') }}</td><td class="px-6 py-3 text-right">{{ number_format($row['depreciation'],2,',',' ') }}</td><td class="px-6 py-3 text-right">{{ number_format($row['accumulated'],2,',',' ') }}</td><td class="px-6 py-3 text-right font-medium">{{ number_format($row['net_book_value'],2,',',' ') }} {{ $asset->currency }}</td></tr>@endforeach</tbody></table></div></div>
    </div></div>
</x-app-layout>
