@php use App\Modules\Administration\Enums\Permission; @endphp
<x-app-layout>
    <x-slot name="header"><div class="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><p class="text-sm font-medium text-indigo-600">Achats</p><h1 class="text-2xl font-semibold text-gray-900">Dépenses et factures fournisseurs</h1></div>@can(Permission::AccountingEntriesCreate->value)<a href="{{ route('expenses.create') }}" class="rounded-lg bg-indigo-600 px-4 py-2.5 text-sm font-semibold text-white">Nouvelle dépense</a>@endcan</div></x-slot>
    <div class="py-10"><div class="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
        @if(session('success'))<div class="mb-6 rounded-lg border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm text-emerald-800">{{ session('success') }}</div>@endif
        <form method="GET" class="mb-6 flex gap-3 rounded-xl bg-white p-4 ring-1 ring-gray-200"><input name="search" value="{{ $search }}" class="min-w-0 flex-1 rounded-md border-gray-300" placeholder="Numéro, fournisseur ou libellé"><x-secondary-button type="submit">Rechercher</x-secondary-button></form>
        <div class="overflow-hidden rounded-xl bg-white shadow-sm ring-1 ring-gray-200"><div class="overflow-x-auto"><table class="min-w-full divide-y divide-gray-200">
            <thead class="bg-gray-50 text-left text-xs uppercase tracking-wide text-gray-500"><tr><th class="px-5 py-3">Dépense</th><th class="px-5 py-3">Fournisseur</th><th class="px-5 py-3">Échéance</th><th class="px-5 py-3">Statut</th><th class="px-5 py-3 text-right">Total</th><th class="px-5 py-3 text-right">Reste à payer</th></tr></thead>
            <tbody class="divide-y divide-gray-100">@forelse($expenses as $expense)<tr><td class="px-5 py-4"><a href="{{ route('expenses.show',$expense) }}" class="font-semibold text-indigo-600">{{ $expense->number }}</a><p class="text-sm text-gray-500">{{ $expense->description }}</p></td><td class="px-5 py-4">{{ $expense->supplier?->name ?? 'Sans fournisseur' }}</td><td class="px-5 py-4">{{ $expense->due_date->format('d/m/Y') }}</td><td class="px-5 py-4"><span class="rounded-full bg-gray-100 px-2.5 py-1 text-xs font-semibold">{{ $expense->status->label() }}</span></td><td class="px-5 py-4 text-right font-semibold">{{ number_format((float)$expense->total,2,',',' ') }} {{ $expense->currency }}</td><td class="px-5 py-4 text-right font-semibold">{{ number_format($expense->balanceDue(),2,',',' ') }} {{ $expense->currency }}</td></tr>@empty<tr><td colspan="6" class="px-6 py-14 text-center text-gray-500">Aucune dépense enregistrée.</td></tr>@endforelse</tbody>
        </table></div>@if($expenses->hasPages())<div class="border-t px-6 py-4">{{ $expenses->links() }}</div>@endif</div>
    </div></div>
</x-app-layout>
