<x-app-layout>
    <x-slot name="header"><div class="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><p class="text-sm font-medium text-indigo-600">Avoir client</p><h1 class="text-2xl font-semibold text-gray-900">{{ $creditNote->number }}</h1><p class="mt-1 text-sm text-gray-500">Détail de l'avoir et de son impact sur le solde de la facture d'origine.</p></div><div class="flex gap-3"><a href="{{ route('credit-notes.print', $creditNote) }}" target="_blank" class="rounded-lg border border-gray-300 bg-white px-4 py-2.5 text-sm font-semibold text-gray-700">Imprimer</a><a href="{{ route('credit-notes.pdf', $creditNote) }}" class="rounded-lg bg-indigo-600 px-4 py-2.5 text-sm font-semibold text-white">PDF</a></div></div></x-slot>
    <div class="py-10"><div class="mx-auto max-w-5xl px-4 sm:px-6 lg:px-8">
        @if (session('success'))<div class="mb-6 rounded-lg border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm text-emerald-800">{{ session('success') }}</div>@endif
        <article class="rounded-xl bg-white p-6 shadow-sm ring-1 ring-gray-200 sm:p-10">
            <div class="grid gap-6 border-b pb-8 sm:grid-cols-2"><div><p class="text-xs uppercase text-gray-500">Client</p><p class="mt-2 text-lg font-semibold">{{ $creditNote->party->name }}</p><p class="mt-2 text-sm text-gray-500">Facture : <a href="{{ route('invoices.show', $creditNote->invoice) }}" class="font-semibold text-indigo-600">{{ $creditNote->invoice->number }}</a></p></div><dl class="grid grid-cols-2 gap-4 text-sm sm:text-right"><div><dt class="text-gray-500">Date</dt><dd class="font-semibold">{{ $creditNote->issue_date->format('d/m/Y') }}</dd></div><div><dt class="text-gray-500">Statut</dt><dd class="font-semibold">{{ $creditNote->status->label() }}</dd></div><div class="col-span-2"><dt class="text-gray-500">Motif</dt><dd class="font-semibold">{{ $creditNote->reason }}</dd></div></dl></div>
            <div class="mt-6 overflow-x-auto"><table class="min-w-full"><thead><tr class="border-b text-left text-xs uppercase text-gray-500"><th class="py-3">Article</th><th class="py-3 text-right">Quantité</th><th class="py-3 text-right">Prix HT</th><th class="py-3 text-right">Taxe</th><th class="py-3 text-right">Total TTC</th></tr></thead><tbody class="divide-y">@foreach($creditNote->lines as $line)<tr><td class="py-4 font-medium">{{ $line->description }}</td><td class="py-4 text-right">{{ number_format((float)$line->quantity,3,',',' ') }}</td><td class="py-4 text-right">{{ number_format((float)$line->unit_price,2,',',' ') }}</td><td class="py-4 text-right">{{ number_format((float)$line->tax_amount,2,',',' ') }}</td><td class="py-4 text-right font-semibold">{{ number_format((float)$line->total,2,',',' ') }}</td></tr>@endforeach</tbody></table></div>
            <div class="mt-8 flex justify-end"><dl class="w-full max-w-sm space-y-3"><div class="flex justify-between"><dt>Sous-total HT</dt><dd>{{ number_format((float)$creditNote->subtotal,2,',',' ') }} {{ $creditNote->currency }}</dd></div><div class="flex justify-between"><dt>Remises</dt><dd>− {{ number_format((float)$creditNote->discount_total,2,',',' ') }}</dd></div><div class="flex justify-between"><dt>Taxes</dt><dd>{{ number_format((float)$creditNote->tax_total,2,',',' ') }}</dd></div><div class="flex justify-between border-t pt-4 text-lg font-semibold"><dt>Total crédité</dt><dd>{{ number_format((float)$creditNote->total,2,',',' ') }} {{ $creditNote->currency }}</dd></div></dl></div>
        </article>
    </div></div>
</x-app-layout>
